# turn off notifications until build is stable
notifications:
  email: false
language: python
os: linux
python:
  - '3.5'
  - '3.6'
before_install: |
 if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
   # Recommended for pyenv
   brew outdated openssl || brew upgrade openssl
   brew outdated readline || brew upgrade readline
   # Update pyenv
   brew outdated pyenv || brew upgrade pyenv
   # Install specified Python version
   pyenv install $PYTHON
   # Set environment variables
   export PYENV_VERSION=$PYTHON
   export PATH="/Users/travis/.pyenv/shims:${PATH}"
   # Confirm versions
   python --version
   pip -V
 fi
install:
  - pip install --upgrade pip
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/test_requirements.txt
  - pip install -r requirements/integration_test_requirements.txt -q
  # work around issues with GPy and GPyOpt setting matplotlib backend
  - "echo 'backend: Agg' > matplotlibrc"
  - pip install .
  - pip freeze
script:
  # - flake8
  - python -m pytest
  - pytest -c /dev/null integration_tests
after_success:
  - codecov
jobs:
  include:
    - os: osx
      language: generic
      env: PYTHON=3.5.2
    - os: osx
      language: generic
      env: PYTHON=3.6.6
